### ISSUE TITLE
Keyboard Layout Editor rendering issue

### ISSUE THREAD

**Issue by chatelao** [JanLunge/pog#38] opened 2024-09-08 17:57 UTC
I get this layout editor missalignement. What files do you need to fix it?

![image](https://github.com/user-attachments/assets/3e0bb599-7a40-46c3-9a51-2626441a9601)

**Comment by JanLunge** [comment] 2024-09-08 18:53
Theree seems to be an issue with the height calculations when the keyboard is taller than wide on startup. For now you can resize the window a bit and it should update the keyboard size to fit

**Comment by JanLunge** [comment] 2024-09-08 18:55
I was able to reproduce the issue so I don't need any more info to fix it thank you for the issue creation.

**Comment by chatelao** [comment] 2024-09-08 20:28
Danke für die prompte Antwort ♥️

**Comment by JanLunge** [comment] 2024-10-04 08:48
should be fixed in the next release

**Closed by JanLunge** 2024-10-04 08:48 UTC
